### ISSUE TITLE
Error Finding AuthStore

### ISSUE THREAD

**Issue by joshua1** [sakulstra/firebase-nextjs-mobx#42]
Hi @sakulstra I get the below error trying to run this repo after yarn install of all node modules 
```
Error: MobX observer: Store 'AuthStore' is not available! Make sure it is provided by some Provider
Error: MobX observer: Store 'AuthStore' is not available! Make sure it is provided by some Provider
    at http://localhost:3000/_next/-/commons.js:5012:46
    at Array.forEach (native)
    at http://localhost:3000/_next/-/commons.js:5009:17
    at _fn.render (http://localhost:3000/_next/-/commons.js:4988:31)
    at _fn.render (http://localhost:3000/_next/-/main.js:10112:30)
    at _fn.withHandleError (http://localhost:3000/_next/-/main.js:4468:17)
    at _fn [as render] (http://localhost:3000/_next/-/main.js:4510:24)
    at http://localhost:3000/_next/-/commons.js:27032:21
    at measureLifeCyclePerf (http://localhost:3000/_next/-/commons.js:26311:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/_next/-/commons.js:27031:25)
```
What am i missing 
<img width="1040" alt="screen shot 2017-06-22 at 6 55 26 am" src="https://user-images.githubusercontent.com/557293/27417931-2020b9e4-5718-11e7-95d0-8a54c9fa766a.png">

**Comment by sakulstra** [comment]
sry, seems like i didn't properly lock some things :) - should be fixed on master now (also pushed outdated dependencies)
please close the issue, if it's solved for you

**Comment by sakulstra** [comment]
closing this due to inactivity
